config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, only: [:new, :create]
  resources :blogs, only: [:index]

  # API routes
  namespace :api do
    namespace :v1 do
      post 'login', to: 'sessions#create'
      post 'register', to: 'users#create'
      resources :blogs, only: [:index, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
require 'digest'

class User < ApplicationRecord
  has_many :blogs

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
  validates_confirmation_of :password

  before_save :encrypt_password

  def authenticate(password)
    self.password == encrypt(password)
  end

  private

  def encrypt_password
    self.password = encrypt(password)
  end

  def encrypt(password)
    # You can use any secure hashing algorithm here, for example, SHA-256
    Digest::SHA256.hexdigest(password)
  end
end

app/controllers/api/v1/blogs_controller.rb
module Api
  module V1
    class BlogsController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :authorize_user

      def index
        blogs = current_user.blogs.page(params[:page]).per(10)
        render json: blogs
      end

      def create
        blog = current_user.blogs.build(blog_params)
        if blog.save
          render json: blog, status: :created
        else
          render json: { error: blog.errors.full_messages }, status: :unprocessable_entity
        end
      end

      private

      def blog_params
        params.permit(:title, :content)
      end

      def authorize_user
        head :unauthorized unless current_user
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    class SessionsController < ApplicationController
      protect_from_forgery with: :null_session
      
      def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
          render json: { message: 'Logged in successfully!', user_id: user.id }, status: :ok
        else
          render json: { error: 'Invalid email or password' }, status: :unprocessable_entity
        end
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      protect_from_forgery with: :null_session
      
      def create
        @user = User.new(user_params)
        if @user.save
          render json: { message: 'User was successfully created!', user_id: @user.id }, status: :created
        else
          render json: { error: @user.errors.full_messages.join(', ') }, status: :unprocessable_entity
        end
      end

      private

      def user_params
        params.require(:user).permit(:username, :email, :password)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :require_login

  def index
    @blogs = current_user.blogs.page(params[:page]).per(10)
  end

  private

  def require_login
    unless current_user
      redirect_to login_path, alert: 'You must be logged in to access this section'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to blogs_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to blogs_path, notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out successfully!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    redirect_to blogs_path if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.password == params[:user][:password_confirmation]
      if @user.save
        session[:user_id] = @user.id
        redirect_to blogs_path, notice: 'User was successfully created!'
      else
        render :new
      end
    else
      @user.errors.add(:password_confirmation, "doesn't match Password")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if @blogs.any? %>
  <div class="container mt-5">
    <h1>My Blogs</h1>
    <div class="row">
      <% @blogs.each do |blog| %>
        <div class="col-md-6 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= blog.title %></h5>
              <p class="card-text"><%= blog.content %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= paginate @blogs, theme: 'bootstrap4'  %>
  </div>
<% else %>
  <div class="container mt-5">
    <h1>No blogs found.</h1>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <% if current_user %>
              <li class="nav-item">
                <%= button_to 'Logout', logout_path, method: :delete, class: 'btn btn-outline-danger my-3 my-sm-0' %>
              </li>
            <% else %>
              <% if current_page?(login_path) %>
                <li class="nav-item">
                  <%= link_to 'Signup', new_user_path, class: 'btn btn-outline-success my-3 my-sm-0' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Login', login_path, class: 'btn btn-outline-primary my-3 my-sm-0 mr-2' %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>
  

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <h1>Register</h1>

  <%= form_with(model: @user, url: users_path, html: { class: "mt-5" }) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Register", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>